//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TooltipResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.GlobalResources.TooltipResource", typeof(TooltipResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Management Corporate users 的本地化字符串。
        /// </summary>
        public static string Bloc_ManagerUser {
            get {
                return ResourceManager.GetString("Bloc_ManagerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select resign user 的本地化字符串。
        /// </summary>
        public static string BulkModifyWorker_ExWorker {
            get {
                return ResourceManager.GetString("BulkModifyWorker_ExWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select resign user belongs working group under the state of the order 的本地化字符串。
        /// </summary>
        public static string BulkModifyWorker_OrderStaus {
            get {
                return ResourceManager.GetString("BulkModifyWorker_OrderStaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select resign user working group they belong to 的本地化字符串。
        /// </summary>
        public static string BulkModifyWorker_Team {
            get {
                return ResourceManager.GetString("BulkModifyWorker_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection and resign user group on-the-job user with authority 的本地化字符串。
        /// </summary>
        public static string BulkModifyWorker_User {
            get {
                return ResourceManager.GetString("BulkModifyWorker_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The reason of canceling the order 的本地化字符串。
        /// </summary>
        public static string CancelReason_Name {
            get {
                return ResourceManager.GetString("CancelReason_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment&apos;s Description 的本地化字符串。
        /// </summary>
        public static string Common_Attachment_Description {
            get {
                return ResourceManager.GetString("Common_Attachment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only allow two digit after radix point. 的本地化字符串。
        /// </summary>
        public static string Common_Point2 {
            get {
                return ResourceManager.GetString("Common_Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The login URL by using ADFS method 的本地化字符串。
        /// </summary>
        public static string Company_ADFS_URL {
            get {
                return ResourceManager.GetString("Company_ADFS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Attachment Limits 的本地化字符串。
        /// </summary>
        public static string Company_Attachlimited {
            get {
                return ResourceManager.GetString("Company_Attachlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A single local upload attachment number limit 的本地化字符串。
        /// </summary>
        public static string Company_AttachNumberlimitedLimit {
            get {
                return ResourceManager.GetString("Company_AttachNumberlimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A single local upload attachment size limit 的本地化字符串。
        /// </summary>
        public static string Company_AttachSizeSingelPlacelimitedLimit {
            get {
                return ResourceManager.GetString("Company_AttachSizeSingelPlacelimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Code 的本地化字符串。
        /// </summary>
        public static string Company_Code {
            get {
                return ResourceManager.GetString("Company_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s DateFormat 的本地化字符串。
        /// </summary>
        public static string Company_DateFormat {
            get {
                return ResourceManager.GetString("Company_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Description 的本地化字符串。
        /// </summary>
        public static string Company_Description {
            get {
                return ResourceManager.GetString("Company_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Full Name 的本地化字符串。
        /// </summary>
        public static string Company_DisplayName {
            get {
                return ResourceManager.GetString("Company_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain name of user&apos;s email must follow this setting. If there are multiple restrictions, use &quot;,&quot; to separate. 的本地化字符串。
        /// </summary>
        public static string Company_EmailRestriction {
            get {
                return ResourceManager.GetString("Company_EmailRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Email Sender 的本地化字符串。
        /// </summary>
        public static string Company_EmailSender {
            get {
                return ResourceManager.GetString("Company_EmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Footer Text 的本地化字符串。
        /// </summary>
        public static string Company_FooterText {
            get {
                return ResourceManager.GetString("Company_FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to enable EquipCal function 的本地化字符串。
        /// </summary>
        public static string Company_IsEquip {
            get {
                return ResourceManager.GetString("Company_IsEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Default Language 的本地化字符串。
        /// </summary>
        public static string Company_Language {
            get {
                return ResourceManager.GetString("Company_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Logo 的本地化字符串。
        /// </summary>
        public static string Company_Logo {
            get {
                return ResourceManager.GetString("Company_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Short Name 的本地化字符串。
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recover 的本地化字符串。
        /// </summary>
        public static string Company_Recover {
            get {
                return ResourceManager.GetString("Company_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Remarks 的本地化字符串。
        /// </summary>
        public static string Company_Remarks {
            get {
                return ResourceManager.GetString("Company_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Service Type 的本地化字符串。
        /// </summary>
        public static string Company_ServiceType {
            get {
                return ResourceManager.GetString("Company_ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A single upload attachment size limit 的本地化字符串。
        /// </summary>
        public static string Company_SingleAttachlimitedLimit {
            get {
                return ResourceManager.GetString("Company_SingleAttachlimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspend 的本地化字符串。
        /// </summary>
        public static string Company_Suspend {
            get {
                return ResourceManager.GetString("Company_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Theme 的本地化字符串。
        /// </summary>
        public static string Company_Theme {
            get {
                return ResourceManager.GetString("Company_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s User Limits 的本地化字符串。
        /// </summary>
        public static string Company_UserLimited {
            get {
                return ResourceManager.GetString("Company_UserLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company&apos;s Web Site Type 的本地化字符串。
        /// </summary>
        public static string Company_WebSiteType {
            get {
                return ResourceManager.GetString("Company_WebSiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company area 的本地化字符串。
        /// </summary>
        public static string CompanyPage_Area {
            get {
                return ResourceManager.GetString("CompanyPage_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corporate 的本地化字符串。
        /// </summary>
        public static string CompanyPage_Bloc {
            get {
                return ResourceManager.GetString("CompanyPage_Bloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_EquipmentLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Plan Number Limit. This number limit also suits to Equipment Type Plan. 的本地化字符串。
        /// </summary>
        public static string CompanyPage_EquipmentPlanLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentPlanLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Type Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_EquipmentTypeLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Level Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_LocationLevels {
            get {
                return ResourceManager.GetString("CompanyPage_LocationLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_LocationLimit {
            get {
                return ResourceManager.GetString("CompanyPage_LocationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Online User Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_OnlineUserLimit {
            get {
                return ResourceManager.GetString("CompanyPage_OnlineUserLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Org. Unit Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_OrgUnitLimit {
            get {
                return ResourceManager.GetString("CompanyPage_OrgUnitLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Org. Unit Level Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_OULevels {
            get {
                return ResourceManager.GetString("CompanyPage_OULevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Number  Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_TaskLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TaskLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Type Number  Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_TaskTypeLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TaskTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team Number Limit 的本地化字符串。
        /// </summary>
        public static string CompanyPage_TeamLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TeamLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete User 的本地化字符串。
        /// </summary>
        public static string Delete_User {
            get {
                return ResourceManager.GetString("Delete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Template Name 的本地化字符串。
        /// </summary>
        public static string EmailTemplate_Name {
            get {
                return ResourceManager.GetString("EmailTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item&apos;s Category. 的本地化字符串。
        /// </summary>
        public static string Equip_Category {
            get {
                return ResourceManager.GetString("Equip_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 item Contractor 的本地化字符串。
        /// </summary>
        public static string Equip_Contractor {
            get {
                return ResourceManager.GetString("Equip_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s Name 的本地化字符串。
        /// </summary>
        public static string Equip_ItemName {
            get {
                return ResourceManager.GetString("Equip_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A unique no of the equipment (can be alphanumeric) 的本地化字符串。
        /// </summary>
        public static string Equip_ItemNo {
            get {
                return ResourceManager.GetString("Equip_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It means that there is no plan assigned to this equipment yet 的本地化字符串。
        /// </summary>
        public static string Equip_ItemStatus_All {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green - means that there is no outstanding order at this moment 的本地化字符串。
        /// </summary>
        public static string Equip_ItemStatus_Green {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red - means that the equipment exceeds the planned service date 的本地化字符串。
        /// </summary>
        public static string Equip_ItemStatus_Red {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow - means that the equipment is approaching the planned service date 的本地化字符串。
        /// </summary>
        public static string Equip_ItemStatus_Yellow {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s type 的本地化字符串。
        /// </summary>
        public static string Equip_ItemType {
            get {
                return ResourceManager.GetString("Equip_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s location 的本地化字符串。
        /// </summary>
        public static string Equip_Location {
            get {
                return ResourceManager.GetString("Equip_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s manufacturer 的本地化字符串。
        /// </summary>
        public static string Equip_Manufacturer {
            get {
                return ResourceManager.GetString("Equip_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s model 的本地化字符串。
        /// </summary>
        public static string Equip_Model {
            get {
                return ResourceManager.GetString("Equip_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s name (should be a unique name) 的本地化字符串。
        /// </summary>
        public static string Equip_Name {
            get {
                return ResourceManager.GetString("Equip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s organization unit (OU) 的本地化字符串。
        /// </summary>
        public static string Equip_OrgUnit {
            get {
                return ResourceManager.GetString("Equip_OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For selecting the coresponding parent item. 的本地化字符串。
        /// </summary>
        public static string Equip_ParentItem {
            get {
                return ResourceManager.GetString("Equip_ParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help you to select &apos;Parent item&apos;. If there are too many parent items, you can use this to look for the parent item. 的本地化字符串。
        /// </summary>
        public static string Equip_ParentItemType {
            get {
                return ResourceManager.GetString("Equip_ParentItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define the number of days the notification to be sent out prior to the service/inspection due date 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_AlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_AlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To define the frequency the reminder notificaiton should be sent  (after issued the first notification) 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_AlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_AlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instruction/steps for the technicans to service/maintain an equipment. 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_Check {
            get {
                return ResourceManager.GetString("Equip_Plan_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The plan&apos;s description 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_ContentDesc {
            get {
                return ResourceManager.GetString("Equip_Plan_ContentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value to define the estimated service hours required for servicing the item 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_EstimateServiceDuration {
            get {
                return ResourceManager.GetString("Equip_Plan_EstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define the first service date 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_FirstServiceDate {
            get {
                return ResourceManager.GetString("Equip_Plan_FirstServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A interval (numeric value) between each service period 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_Interval {
            get {
                return ResourceManager.GetString("Equip_Plan_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Gen Alarming Day 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_ManualGenAlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_ManualGenAlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Gen Alarming Interval Day 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_ManualGenAlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_ManualGenAlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A unique name of the plan 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_Name {
            get {
                return ResourceManager.GetString("Equip_Plan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other reason 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_Other {
            get {
                return ResourceManager.GetString("Equip_Plan_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qualification of a technican who can carry out the inspection/service. 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_Qualification {
            get {
                return ResourceManager.GetString("Equip_Plan_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define the number of days the notification to be sent out prior to the repair due date. 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_RepairAlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_RepairAlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after the first alarm day, alarm interval day 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_RepairAlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_RepairAlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 requirement description 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_RequirementDesc {
            get {
                return ResourceManager.GetString("Equip_Plan_RequirementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the primary person who in charge this item&apos;s service. 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_ServiceBy {
            get {
                return ResourceManager.GetString("Equip_Plan_ServiceBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the vice-person who in charge this item&apos;s service. 的本地化字符串。
        /// </summary>
        public static string Equip_Plan_ServiceBy2 {
            get {
                return ResourceManager.GetString("Equip_Plan_ServiceBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something shulde be pay attention to when service this item. 的本地化字符串。
        /// </summary>
        public static string Equip_Remark {
            get {
                return ResourceManager.GetString("Equip_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s supplier 的本地化字符串。
        /// </summary>
        public static string Equip_Supplier {
            get {
                return ResourceManager.GetString("Equip_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Description 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_Descrption {
            get {
                return ResourceManager.GetString("EquipType_Item_Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Manufacturer 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_Manftr {
            get {
                return ResourceManager.GetString("EquipType_Item_Manftr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Model 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_Model {
            get {
                return ResourceManager.GetString("EquipType_Item_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Name 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_Name {
            get {
                return ResourceManager.GetString("EquipType_Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Number 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_No {
            get {
                return ResourceManager.GetString("EquipType_Item_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Predefine Name 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_PredefineName {
            get {
                return ResourceManager.GetString("EquipType_Item_PredefineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Template&apos;s Service Remark 的本地化字符串。
        /// </summary>
        public static string EquipType_Item_Remark {
            get {
                return ResourceManager.GetString("EquipType_Item_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Alarming Level,value must be number 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_AlarmLevel {
            get {
                return ResourceManager.GetString("EquipType_Plan_AlarmLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Alarming Level Interval,value must be number 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_AlarmLevelInterval {
            get {
                return ResourceManager.GetString("EquipType_Plan_AlarmLevelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Estimate Duration,must be number 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_EstiaSerDuration {
            get {
                return ResourceManager.GetString("EquipType_Plan_EstiaSerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Maintance Check 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_MaintCheck {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description of Item Template Plan&apos;s Maintance Content  的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_MaintConDesc {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintConDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description of ItemTemplate Plan&apos;s User Maintance Requirement 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_MaintUserRequirDesc {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintUserRequirDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Name 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_Name {
            get {
                return ResourceManager.GetString("EquipType_Plan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Other Request 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_OtherRequest {
            get {
                return ResourceManager.GetString("EquipType_Plan_OtherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Repair Level,value must be number 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_RepairLevel {
            get {
                return ResourceManager.GetString("EquipType_Plan_RepairLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Template Plan&apos;s Repair Level Interval,value must be number 的本地化字符串。
        /// </summary>
        public static string EquipType_Plan_RepairLevelInterval {
            get {
                return ResourceManager.GetString("EquipType_Plan_RepairLevelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project fault code 的本地化字符串。
        /// </summary>
        public static string FaultCode_Name {
            get {
                return ResourceManager.GetString("FaultCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approved By : 的本地化字符串。
        /// </summary>
        public static string LabelReport_ApprovedBy {
            get {
                return ResourceManager.GetString("LabelReport_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cal. By : 的本地化字符串。
        /// </summary>
        public static string LabelReport_CalBy {
            get {
                return ResourceManager.GetString("LabelReport_CalBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked By : 的本地化字符串。
        /// </summary>
        public static string LabelReport_CheckBy {
            get {
                return ResourceManager.GetString("LabelReport_CheckBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date : 的本地化字符串。
        /// </summary>
        public static string LabelReport_Date {
            get {
                return ResourceManager.GetString("LabelReport_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eqm. No. : 的本地化字符串。
        /// </summary>
        public static string LabelReport_EquipmentNo {
            get {
                return ResourceManager.GetString("LabelReport_EquipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ext. Date : 的本地化字符串。
        /// </summary>
        public static string LabelReport_ExtDate {
            get {
                return ResourceManager.GetString("LabelReport_ExtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next : 的本地化字符串。
        /// </summary>
        public static string LabelReport_Next {
            get {
                return ResourceManager.GetString("LabelReport_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CALIBRATION 的本地化字符串。
        /// </summary>
        public static string LabelReport_State_calibration {
            get {
                return ResourceManager.GetString("LabelReport_State_calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHECKING 的本地化字符串。
        /// </summary>
        public static string LabelReport_State_checking {
            get {
                return ResourceManager.GetString("LabelReport_State_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXTENDED SERVICE 的本地化字符串。
        /// </summary>
        public static string LabelReport_State_extended {
            get {
                return ResourceManager.GetString("LabelReport_State_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INACTIVE 的本地化字符串。
        /// </summary>
        public static string LabelReport_State_inactive {
            get {
                return ResourceManager.GetString("LabelReport_State_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 REFERENCE CALIBRATION STANDARD 的本地化字符串。
        /// </summary>
        public static string LabelReport_State_Reference {
            get {
                return ResourceManager.GetString("LabelReport_State_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verified By : 的本地化字符串。
        /// </summary>
        public static string LabelReport_VerifiedBy {
            get {
                return ResourceManager.GetString("LabelReport_VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project&apos;s location 的本地化字符串。
        /// </summary>
        public static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project&apos;s parent location 的本地化字符串。
        /// </summary>
        public static string Location_ParentName {
            get {
                return ResourceManager.GetString("Location_ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;] Name 的本地化字符串。
        /// </summary>
        public static string MaintSummary_ItemName {
            get {
                return ResourceManager.GetString("MaintSummary_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item&apos;s type. 的本地化字符串。
        /// </summary>
        public static string MaintSummary_ItemType {
            get {
                return ResourceManager.GetString("MaintSummary_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;]&apos;s [&apos;Location&apos;]. 的本地化字符串。
        /// </summary>
        public static string MaintSummary_Location {
            get {
                return ResourceManager.GetString("MaintSummary_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;]&apos;s [&apos;MasterCategory&apos;] 的本地化字符串。
        /// </summary>
        public static string MaintSummary_MasterCategory {
            get {
                return ResourceManager.GetString("MaintSummary_MasterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [&apos;Item&apos;]&apos;s Org. Unit. 的本地化字符串。
        /// </summary>
        public static string MaintSummary_OrgUnit {
            get {
                return ResourceManager.GetString("MaintSummary_OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service order type (fixed/flow) 的本地化字符串。
        /// </summary>
        public static string MaintSummary_PlanTypeCategory {
            get {
                return ResourceManager.GetString("MaintSummary_PlanTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Annual plan of the repair order or had done service order. 的本地化字符串。
        /// </summary>
        public static string MaintSummary_ViewCategory {
            get {
                return ResourceManager.GetString("MaintSummary_ViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search summary for specified year. 的本地化字符串。
        /// </summary>
        public static string MaintSummary_Year {
            get {
                return ResourceManager.GetString("MaintSummary_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection function switch will affect this switch, if the inspection function is turned off, this switch will automatically set to close. 的本地化字符串。
        /// </summary>
        public static string MasterOrderSwitchDescription {
            get {
                return ResourceManager.GetString("MasterOrderSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to approve the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_ApproveBy {
            get {
                return ResourceManager.GetString("OrderPage_ApproveBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the approve order result 的本地化字符串。
        /// </summary>
        public static string OrderPage_ApproveResult {
            get {
                return ResourceManager.GetString("OrderPage_ApproveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recode the approve order remark 的本地化字符串。
        /// </summary>
        public static string OrderPage_ApproveResultRemark {
            get {
                return ResourceManager.GetString("OrderPage_ApproveResultRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to cal the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalBy {
            get {
                return ResourceManager.GetString("OrderPage_CalBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the completion date for actually calibration 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_CalCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order&apos;s estimate service date 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalEstimateServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_CalEstimateServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order&apos;s estimate service duration 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalEstimateServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_CalEstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recode the cal order remark 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalRemarkTitle {
            get {
                return ResourceManager.GetString("OrderPage_CalRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the cal order result 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalResult {
            get {
                return ResourceManager.GetString("OrderPage_CalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the actual duration for cal order 的本地化字符串。
        /// </summary>
        public static string OrderPage_CalServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_CalServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a reason to cancel the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_CancelReason {
            get {
                return ResourceManager.GetString("OrderPage_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to check the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_CheckBy {
            get {
                return ResourceManager.GetString("OrderPage_CheckBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to check in the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_CheckInBy {
            get {
                return ResourceManager.GetString("OrderPage_CheckInBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check In Date 的本地化字符串。
        /// </summary>
        public static string OrderPage_CheckInDate {
            get {
                return ResourceManager.GetString("OrderPage_CheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the check order result 的本地化字符串。
        /// </summary>
        public static string OrderPage_CheckResult {
            get {
                return ResourceManager.GetString("OrderPage_CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recode the check order remark 的本地化字符串。
        /// </summary>
        public static string OrderPage_CheckResultRemark {
            get {
                return ResourceManager.GetString("OrderPage_CheckResultRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a order&apos;s control 的本地化字符串。
        /// </summary>
        public static string OrderPage_Control {
            get {
                return ResourceManager.GetString("OrderPage_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input a date to extend the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_ExtendServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_ExtendServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Party 的本地化字符串。
        /// </summary>
        public static string OrderPage_ExternalParty {
            get {
                return ResourceManager.GetString("OrderPage_ExternalParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Up 的本地化字符串。
        /// </summary>
        public static string OrderPage_FollowUp {
            get {
                return ResourceManager.GetString("OrderPage_FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Up Date 的本地化字符串。
        /// </summary>
        public static string OrderPage_FollowUpDate {
            get {
                return ResourceManager.GetString("OrderPage_FollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to inspection the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_InspectionBy {
            get {
                return ResourceManager.GetString("OrderPage_InspectionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order is Internal or External 的本地化字符串。
        /// </summary>
        public static string OrderPage_InternalExternal {
            get {
                return ResourceManager.GetString("OrderPage_InternalExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order is priority 的本地化字符串。
        /// </summary>
        public static string OrderPage_IsPriority {
            get {
                return ResourceManager.GetString("OrderPage_IsPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the completion date for maint(repair) order 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order&apos;s estimate service date 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintEstimateServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintEstimateServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order&apos;s estimate service duration 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintEstimateServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_MaintEstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maint order&apos;s follow up date 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintFollowUpDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintFollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recode the maint order remark 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintRemarkTitle {
            get {
                return ResourceManager.GetString("OrderPage_MaintRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the maint order result 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintResultTitle {
            get {
                return ResourceManager.GetString("OrderPage_MaintResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the duration for maint(repair) order 的本地化字符串。
        /// </summary>
        public static string OrderPage_MaintServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_MaintServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to measure the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_MeasureBy {
            get {
                return ResourceManager.GetString("OrderPage_MeasureBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input next cal date 的本地化字符串。
        /// </summary>
        public static string OrderPage_NextCalDate {
            get {
                return ResourceManager.GetString("OrderPage_NextCalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recode the order remark 的本地化字符串。
        /// </summary>
        public static string OrderPage_Remark {
            get {
                return ResourceManager.GetString("OrderPage_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a user to review the order 的本地化字符串。
        /// </summary>
        public static string OrderPage_ReviewBy {
            get {
                return ResourceManager.GetString("OrderPage_ReviewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the review order result 的本地化字符串。
        /// </summary>
        public static string OrderPage_ReviewResult {
            get {
                return ResourceManager.GetString("OrderPage_ReviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the standard deviation for order 的本地化字符串。
        /// </summary>
        public static string OrderPage_StandardDeviation {
            get {
                return ResourceManager.GetString("OrderPage_StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the completion date for task order 的本地化字符串。
        /// </summary>
        public static string OrderPage_TaskCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_TaskCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the TI&apos;s word content 的本地化字符串。
        /// </summary>
        public static string OrderPage_WordContent {
            get {
                return ResourceManager.GetString("OrderPage_WordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrgUnit&apos;s Name 的本地化字符串。
        /// </summary>
        public static string OrgUnit_Name {
            get {
                return ResourceManager.GetString("OrgUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To create a new [&apos;Item&apos;], you can select an &quot;[&apos;Item&apos;] Template&quot; for editing.  Alternatively, you can select &quot;Empty Template&quot; to start from scratch. 的本地化字符串。
        /// </summary>
        public static string Page_Templation {
            get {
                return ResourceManager.GetString("Page_Templation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether a password containing letters 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_ContainLetter {
            get {
                return ResourceManager.GetString("PasswordPolicy_ContainLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether a password containing number 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_ContainNumber {
            get {
                return ResourceManager.GetString("PasswordPolicy_ContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum password length 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_MaxLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum letter times 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_MinEnLetterLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MinEnLetterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum password length 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_MinLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether a password containing special char 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_NeedSpecialChar {
            get {
                return ResourceManager.GetString("PasswordPolicy_NeedSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether a password containing space 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_NoBlankSpace {
            get {
                return ResourceManager.GetString("PasswordPolicy_NoBlankSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Repeat Interval frequency 的本地化字符串。
        /// </summary>
        public static string PasswordPolicy_UnlikePrePwdCount {
            get {
                return ResourceManager.GetString("PasswordPolicy_UnlikePrePwdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turnaround Time Analysis Service month 的本地化字符串。
        /// </summary>
        public static string Report_TurnaroundTimeAnalysis_ServiceMonth {
            get {
                return ResourceManager.GetString("Report_TurnaroundTimeAnalysis_ServiceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Formating 的本地化字符串。
        /// </summary>
        public static string Report_Type {
            get {
                return ResourceManager.GetString("Report_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve {0} order while order is complete. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationApproval {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign this calibration order&apos;s work memebers and managent memebers. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationAssign {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check in {0} order. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationCheckIn {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extend(Delayed) {0} order. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationExtend {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review {0} order while order is in approval. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationReview {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign memebers for this {0} order. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CommonAssign {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel this {0} order. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CommonCancel {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check in {0} order while order is complete. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CommonCheckIn {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute {0} work for {0} order. 的本地化字符串。
        /// </summary>
        public static string ServiceOrderActionDetail_CommonExecute {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        public static string SystemCheck_Body {
            get {
                return ResourceManager.GetString("SystemCheck_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiver 的本地化字符串。
        /// </summary>
        public static string SystemCheck_Receiver {
            get {
                return ResourceManager.GetString("SystemCheck_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        public static string SystemCheck_Subject {
            get {
                return ResourceManager.GetString("SystemCheck_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Management Item 的本地化字符串。
        /// </summary>
        public static string TaskPage_ManagementItem {
            get {
                return ResourceManager.GetString("TaskPage_ManagementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need Notify 的本地化字符串。
        /// </summary>
        public static string TaskPage_NeedNotify {
            get {
                return ResourceManager.GetString("TaskPage_NeedNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        public static string TaskPage_Project {
            get {
                return ResourceManager.GetString("TaskPage_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Risk Level 的本地化字符串。
        /// </summary>
        public static string TaskPage_RiskLevel {
            get {
                return ResourceManager.GetString("TaskPage_RiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspection function switch will affect this switch, if the inspection function is turned off, this switch will automatically set to close. 的本地化字符串。
        /// </summary>
        public static string TaskSwitchDescription {
            get {
                return ResourceManager.GetString("TaskSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Template&apos;s Management Item 的本地化字符串。
        /// </summary>
        public static string TaskTypePage_ManagementItem {
            get {
                return ResourceManager.GetString("TaskTypePage_ManagementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Template&apos;s Project 的本地化字符串。
        /// </summary>
        public static string TaskTypePage_Project {
            get {
                return ResourceManager.GetString("TaskTypePage_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Template&apos;s Remark 的本地化字符串。
        /// </summary>
        public static string TaskTypePage_Remark {
            get {
                return ResourceManager.GetString("TaskTypePage_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Template&apos;s Name, must be unique 的本地化字符串。
        /// </summary>
        public static string TaskTypePage_TaskTypeName {
            get {
                return ResourceManager.GetString("TaskTypePage_TaskTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Template&apos;s Risk Level 的本地化字符串。
        /// </summary>
        public static string TaskTypePage_TaskTypeRiskLevel {
            get {
                return ResourceManager.GetString("TaskTypePage_TaskTypeRiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team&apos;s Description 的本地化字符串。
        /// </summary>
        public static string Team_Description {
            get {
                return ResourceManager.GetString("Team_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team&apos;s Name 的本地化字符串。
        /// </summary>
        public static string Team_Name {
            get {
                return ResourceManager.GetString("Team_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team&apos;s Type 的本地化字符串。
        /// </summary>
        public static string Team_TeamType {
            get {
                return ResourceManager.GetString("Team_TeamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team&apos;s Users 的本地化字符串。
        /// </summary>
        public static string Team_User {
            get {
                return ResourceManager.GetString("Team_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Company.If user doesn&apos;t only have Sysadmin Administrator Role, Company is require. 的本地化字符串。
        /// </summary>
        public static string User_Company {
            get {
                return ResourceManager.GetString("User_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Email 的本地化字符串。
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Full Name 的本地化字符串。
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users access the default language 的本地化字符串。
        /// </summary>
        public static string User_Language {
            get {
                return ResourceManager.GetString("User_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Logon Name 的本地化字符串。
        /// </summary>
        public static string User_LogonName {
            get {
                return ResourceManager.GetString("User_LogonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Roles 的本地化字符串。
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Title 的本地化字符串。
        /// </summary>
        public static string UserPage_Title_Colon {
            get {
                return ResourceManager.GetString("UserPage_Title_Colon", resourceCulture);
            }
        }
    }
}
