//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_FromDBEFDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_SiteMap_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_SiteMap_Menu()
        {
            this.Common_SiteMap_Menu1 = new HashSet<Common_SiteMap_Menu>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ResourceKey { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string ActionName { get; set; }
        public string RouteValues { get; set; }
        public bool IsSkip { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_SiteMap_Menu> Common_SiteMap_Menu1 { get; set; }
        public virtual Common_SiteMap_Menu Common_SiteMap_Menu2 { get; set; }
    }
}
