//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_FromDBEFDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Authen_FunctionPermissionLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_Authen_FunctionPermissionLevel()
        {
            this.Common_Authen_ControllerActions = new HashSet<Common_Authen_ControllerActions>();
            this.Common_Authen_RoleFunctionPermission = new HashSet<Common_Authen_RoleFunctionPermission>();
        }
    
        public int ID { get; set; }
        public string FunctionName { get; set; }
        public string PermissionLevel { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_Authen_ControllerActions> Common_Authen_ControllerActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_Authen_RoleFunctionPermission> Common_Authen_RoleFunctionPermission { get; set; }
    }
}
