//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_FromDBEFDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Authen_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_Authen_User()
        {
            this.Common_Authen_RoleUser = new HashSet<Common_Authen_RoleUser>();
        }
    
        public int UserID { get; set; }
        public string LogonName { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> DateOFBirth { get; set; }
        public int Status { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_Authen_RoleUser> Common_Authen_RoleUser { get; set; }
    }
}
