//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_FromDBEFDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_4
    {
        public string id { get; set; }
        public string name { get; set; }
        public string pid { get; set; }
    
        public virtual Table_2 Table_2 { get; set; }
    }
}
