//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TooltipResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.GlobalResources.TooltipResource", typeof(TooltipResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Corporate users.
        /// </summary>
        public static string Bloc_ManagerUser {
            get {
                return ResourceManager.GetString("Bloc_ManagerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resign user.
        /// </summary>
        public static string BulkModifyWorker_ExWorker {
            get {
                return ResourceManager.GetString("BulkModifyWorker_ExWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resign user belongs working group under the state of the order.
        /// </summary>
        public static string BulkModifyWorker_OrderStaus {
            get {
                return ResourceManager.GetString("BulkModifyWorker_OrderStaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resign user working group they belong to.
        /// </summary>
        public static string BulkModifyWorker_Team {
            get {
                return ResourceManager.GetString("BulkModifyWorker_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection and resign user group on-the-job user with authority.
        /// </summary>
        public static string BulkModifyWorker_User {
            get {
                return ResourceManager.GetString("BulkModifyWorker_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason of canceling the order.
        /// </summary>
        public static string CancelReason_Name {
            get {
                return ResourceManager.GetString("CancelReason_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment&apos;s Description.
        /// </summary>
        public static string Common_Attachment_Description {
            get {
                return ResourceManager.GetString("Common_Attachment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allow two digit after radix point..
        /// </summary>
        public static string Common_Point2 {
            get {
                return ResourceManager.GetString("Common_Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login URL by using ADFS method.
        /// </summary>
        public static string Company_ADFS_URL {
            get {
                return ResourceManager.GetString("Company_ADFS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Attachment Limits.
        /// </summary>
        public static string Company_Attachlimited {
            get {
                return ResourceManager.GetString("Company_Attachlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single local upload attachment number limit.
        /// </summary>
        public static string Company_AttachNumberlimitedLimit {
            get {
                return ResourceManager.GetString("Company_AttachNumberlimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single local upload attachment size limit.
        /// </summary>
        public static string Company_AttachSizeSingelPlacelimitedLimit {
            get {
                return ResourceManager.GetString("Company_AttachSizeSingelPlacelimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Code.
        /// </summary>
        public static string Company_Code {
            get {
                return ResourceManager.GetString("Company_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s DateFormat.
        /// </summary>
        public static string Company_DateFormat {
            get {
                return ResourceManager.GetString("Company_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Description.
        /// </summary>
        public static string Company_Description {
            get {
                return ResourceManager.GetString("Company_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Full Name.
        /// </summary>
        public static string Company_DisplayName {
            get {
                return ResourceManager.GetString("Company_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name of user&apos;s email must follow this setting. If there are multiple restrictions, use &quot;,&quot; to separate..
        /// </summary>
        public static string Company_EmailRestriction {
            get {
                return ResourceManager.GetString("Company_EmailRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Email Sender.
        /// </summary>
        public static string Company_EmailSender {
            get {
                return ResourceManager.GetString("Company_EmailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Footer Text.
        /// </summary>
        public static string Company_FooterText {
            get {
                return ResourceManager.GetString("Company_FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to enable EquipCal function.
        /// </summary>
        public static string Company_IsEquip {
            get {
                return ResourceManager.GetString("Company_IsEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Default Language.
        /// </summary>
        public static string Company_Language {
            get {
                return ResourceManager.GetString("Company_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Logo.
        /// </summary>
        public static string Company_Logo {
            get {
                return ResourceManager.GetString("Company_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Short Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Company_Recover {
            get {
                return ResourceManager.GetString("Company_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Remarks.
        /// </summary>
        public static string Company_Remarks {
            get {
                return ResourceManager.GetString("Company_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Service Type.
        /// </summary>
        public static string Company_ServiceType {
            get {
                return ResourceManager.GetString("Company_ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single upload attachment size limit.
        /// </summary>
        public static string Company_SingleAttachlimitedLimit {
            get {
                return ResourceManager.GetString("Company_SingleAttachlimitedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Company_Suspend {
            get {
                return ResourceManager.GetString("Company_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Theme.
        /// </summary>
        public static string Company_Theme {
            get {
                return ResourceManager.GetString("Company_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s User Limits.
        /// </summary>
        public static string Company_UserLimited {
            get {
                return ResourceManager.GetString("Company_UserLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Web Site Type.
        /// </summary>
        public static string Company_WebSiteType {
            get {
                return ResourceManager.GetString("Company_WebSiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company area.
        /// </summary>
        public static string CompanyPage_Area {
            get {
                return ResourceManager.GetString("CompanyPage_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string CompanyPage_Bloc {
            get {
                return ResourceManager.GetString("CompanyPage_Bloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Number Limit.
        /// </summary>
        public static string CompanyPage_EquipmentLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Plan Number Limit. This number limit also suits to Equipment Type Plan..
        /// </summary>
        public static string CompanyPage_EquipmentPlanLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentPlanLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type Number Limit.
        /// </summary>
        public static string CompanyPage_EquipmentTypeLimit {
            get {
                return ResourceManager.GetString("CompanyPage_EquipmentTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Level Limit.
        /// </summary>
        public static string CompanyPage_LocationLevels {
            get {
                return ResourceManager.GetString("CompanyPage_LocationLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Number Limit.
        /// </summary>
        public static string CompanyPage_LocationLimit {
            get {
                return ResourceManager.GetString("CompanyPage_LocationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Online User Number Limit.
        /// </summary>
        public static string CompanyPage_OnlineUserLimit {
            get {
                return ResourceManager.GetString("CompanyPage_OnlineUserLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org. Unit Number Limit.
        /// </summary>
        public static string CompanyPage_OrgUnitLimit {
            get {
                return ResourceManager.GetString("CompanyPage_OrgUnitLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org. Unit Level Limit.
        /// </summary>
        public static string CompanyPage_OULevels {
            get {
                return ResourceManager.GetString("CompanyPage_OULevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Number  Limit.
        /// </summary>
        public static string CompanyPage_TaskLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TaskLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type Number  Limit.
        /// </summary>
        public static string CompanyPage_TaskTypeLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TaskTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Number Limit.
        /// </summary>
        public static string CompanyPage_TeamLimit {
            get {
                return ResourceManager.GetString("CompanyPage_TeamLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string Delete_User {
            get {
                return ResourceManager.GetString("Delete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Name.
        /// </summary>
        public static string EmailTemplate_Name {
            get {
                return ResourceManager.GetString("EmailTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item&apos;s Category..
        /// </summary>
        public static string Equip_Category {
            get {
                return ResourceManager.GetString("Equip_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item Contractor.
        /// </summary>
        public static string Equip_Contractor {
            get {
                return ResourceManager.GetString("Equip_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s Name.
        /// </summary>
        public static string Equip_ItemName {
            get {
                return ResourceManager.GetString("Equip_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique no of the equipment (can be alphanumeric).
        /// </summary>
        public static string Equip_ItemNo {
            get {
                return ResourceManager.GetString("Equip_ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It means that there is no plan assigned to this equipment yet.
        /// </summary>
        public static string Equip_ItemStatus_All {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green - means that there is no outstanding order at this moment.
        /// </summary>
        public static string Equip_ItemStatus_Green {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red - means that the equipment exceeds the planned service date.
        /// </summary>
        public static string Equip_ItemStatus_Red {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow - means that the equipment is approaching the planned service date.
        /// </summary>
        public static string Equip_ItemStatus_Yellow {
            get {
                return ResourceManager.GetString("Equip_ItemStatus_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s type.
        /// </summary>
        public static string Equip_ItemType {
            get {
                return ResourceManager.GetString("Equip_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s location.
        /// </summary>
        public static string Equip_Location {
            get {
                return ResourceManager.GetString("Equip_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s manufacturer.
        /// </summary>
        public static string Equip_Manufacturer {
            get {
                return ResourceManager.GetString("Equip_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s model.
        /// </summary>
        public static string Equip_Model {
            get {
                return ResourceManager.GetString("Equip_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s name (should be a unique name).
        /// </summary>
        public static string Equip_Name {
            get {
                return ResourceManager.GetString("Equip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s organization unit (OU).
        /// </summary>
        public static string Equip_OrgUnit {
            get {
                return ResourceManager.GetString("Equip_OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For selecting the coresponding parent item..
        /// </summary>
        public static string Equip_ParentItem {
            get {
                return ResourceManager.GetString("Equip_ParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help you to select &apos;Parent item&apos;. If there are too many parent items, you can use this to look for the parent item..
        /// </summary>
        public static string Equip_ParentItemType {
            get {
                return ResourceManager.GetString("Equip_ParentItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the number of days the notification to be sent out prior to the service/inspection due date.
        /// </summary>
        public static string Equip_Plan_AlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_AlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To define the frequency the reminder notificaiton should be sent  (after issued the first notification).
        /// </summary>
        public static string Equip_Plan_AlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_AlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction/steps for the technicans to service/maintain an equipment..
        /// </summary>
        public static string Equip_Plan_Check {
            get {
                return ResourceManager.GetString("Equip_Plan_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan&apos;s description.
        /// </summary>
        public static string Equip_Plan_ContentDesc {
            get {
                return ResourceManager.GetString("Equip_Plan_ContentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value to define the estimated service hours required for servicing the item.
        /// </summary>
        public static string Equip_Plan_EstimateServiceDuration {
            get {
                return ResourceManager.GetString("Equip_Plan_EstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the first service date.
        /// </summary>
        public static string Equip_Plan_FirstServiceDate {
            get {
                return ResourceManager.GetString("Equip_Plan_FirstServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A interval (numeric value) between each service period.
        /// </summary>
        public static string Equip_Plan_Interval {
            get {
                return ResourceManager.GetString("Equip_Plan_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Gen Alarming Day.
        /// </summary>
        public static string Equip_Plan_ManualGenAlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_ManualGenAlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Gen Alarming Interval Day.
        /// </summary>
        public static string Equip_Plan_ManualGenAlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_ManualGenAlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique name of the plan.
        /// </summary>
        public static string Equip_Plan_Name {
            get {
                return ResourceManager.GetString("Equip_Plan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reason.
        /// </summary>
        public static string Equip_Plan_Other {
            get {
                return ResourceManager.GetString("Equip_Plan_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification of a technican who can carry out the inspection/service..
        /// </summary>
        public static string Equip_Plan_Qualification {
            get {
                return ResourceManager.GetString("Equip_Plan_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the number of days the notification to be sent out prior to the repair due date..
        /// </summary>
        public static string Equip_Plan_RepairAlarmingDay {
            get {
                return ResourceManager.GetString("Equip_Plan_RepairAlarmingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after the first alarm day, alarm interval day.
        /// </summary>
        public static string Equip_Plan_RepairAlarmingIntervalDay {
            get {
                return ResourceManager.GetString("Equip_Plan_RepairAlarmingIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirement description.
        /// </summary>
        public static string Equip_Plan_RequirementDesc {
            get {
                return ResourceManager.GetString("Equip_Plan_RequirementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the primary person who in charge this item&apos;s service..
        /// </summary>
        public static string Equip_Plan_ServiceBy {
            get {
                return ResourceManager.GetString("Equip_Plan_ServiceBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the vice-person who in charge this item&apos;s service..
        /// </summary>
        public static string Equip_Plan_ServiceBy2 {
            get {
                return ResourceManager.GetString("Equip_Plan_ServiceBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something shulde be pay attention to when service this item..
        /// </summary>
        public static string Equip_Remark {
            get {
                return ResourceManager.GetString("Equip_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s supplier.
        /// </summary>
        public static string Equip_Supplier {
            get {
                return ResourceManager.GetString("Equip_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Description.
        /// </summary>
        public static string EquipType_Item_Descrption {
            get {
                return ResourceManager.GetString("EquipType_Item_Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Manufacturer.
        /// </summary>
        public static string EquipType_Item_Manftr {
            get {
                return ResourceManager.GetString("EquipType_Item_Manftr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Model.
        /// </summary>
        public static string EquipType_Item_Model {
            get {
                return ResourceManager.GetString("EquipType_Item_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Name.
        /// </summary>
        public static string EquipType_Item_Name {
            get {
                return ResourceManager.GetString("EquipType_Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Number.
        /// </summary>
        public static string EquipType_Item_No {
            get {
                return ResourceManager.GetString("EquipType_Item_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Predefine Name.
        /// </summary>
        public static string EquipType_Item_PredefineName {
            get {
                return ResourceManager.GetString("EquipType_Item_PredefineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Template&apos;s Service Remark.
        /// </summary>
        public static string EquipType_Item_Remark {
            get {
                return ResourceManager.GetString("EquipType_Item_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Alarming Level,value must be number.
        /// </summary>
        public static string EquipType_Plan_AlarmLevel {
            get {
                return ResourceManager.GetString("EquipType_Plan_AlarmLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Alarming Level Interval,value must be number.
        /// </summary>
        public static string EquipType_Plan_AlarmLevelInterval {
            get {
                return ResourceManager.GetString("EquipType_Plan_AlarmLevelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Estimate Duration,must be number.
        /// </summary>
        public static string EquipType_Plan_EstiaSerDuration {
            get {
                return ResourceManager.GetString("EquipType_Plan_EstiaSerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Maintance Check.
        /// </summary>
        public static string EquipType_Plan_MaintCheck {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Item Template Plan&apos;s Maintance Content .
        /// </summary>
        public static string EquipType_Plan_MaintConDesc {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintConDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of ItemTemplate Plan&apos;s User Maintance Requirement.
        /// </summary>
        public static string EquipType_Plan_MaintUserRequirDesc {
            get {
                return ResourceManager.GetString("EquipType_Plan_MaintUserRequirDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Name.
        /// </summary>
        public static string EquipType_Plan_Name {
            get {
                return ResourceManager.GetString("EquipType_Plan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Other Request.
        /// </summary>
        public static string EquipType_Plan_OtherRequest {
            get {
                return ResourceManager.GetString("EquipType_Plan_OtherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Repair Level,value must be number.
        /// </summary>
        public static string EquipType_Plan_RepairLevel {
            get {
                return ResourceManager.GetString("EquipType_Plan_RepairLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Plan&apos;s Repair Level Interval,value must be number.
        /// </summary>
        public static string EquipType_Plan_RepairLevelInterval {
            get {
                return ResourceManager.GetString("EquipType_Plan_RepairLevelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project fault code.
        /// </summary>
        public static string FaultCode_Name {
            get {
                return ResourceManager.GetString("FaultCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By :.
        /// </summary>
        public static string LabelReport_ApprovedBy {
            get {
                return ResourceManager.GetString("LabelReport_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal. By :.
        /// </summary>
        public static string LabelReport_CalBy {
            get {
                return ResourceManager.GetString("LabelReport_CalBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked By :.
        /// </summary>
        public static string LabelReport_CheckBy {
            get {
                return ResourceManager.GetString("LabelReport_CheckBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string LabelReport_Date {
            get {
                return ResourceManager.GetString("LabelReport_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eqm. No. :.
        /// </summary>
        public static string LabelReport_EquipmentNo {
            get {
                return ResourceManager.GetString("LabelReport_EquipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext. Date :.
        /// </summary>
        public static string LabelReport_ExtDate {
            get {
                return ResourceManager.GetString("LabelReport_ExtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next :.
        /// </summary>
        public static string LabelReport_Next {
            get {
                return ResourceManager.GetString("LabelReport_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIBRATION.
        /// </summary>
        public static string LabelReport_State_calibration {
            get {
                return ResourceManager.GetString("LabelReport_State_calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKING.
        /// </summary>
        public static string LabelReport_State_checking {
            get {
                return ResourceManager.GetString("LabelReport_State_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTENDED SERVICE.
        /// </summary>
        public static string LabelReport_State_extended {
            get {
                return ResourceManager.GetString("LabelReport_State_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVE.
        /// </summary>
        public static string LabelReport_State_inactive {
            get {
                return ResourceManager.GetString("LabelReport_State_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCE CALIBRATION STANDARD.
        /// </summary>
        public static string LabelReport_State_Reference {
            get {
                return ResourceManager.GetString("LabelReport_State_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified By :.
        /// </summary>
        public static string LabelReport_VerifiedBy {
            get {
                return ResourceManager.GetString("LabelReport_VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s location.
        /// </summary>
        public static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s parent location.
        /// </summary>
        public static string Location_ParentName {
            get {
                return ResourceManager.GetString("Location_ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;] Name.
        /// </summary>
        public static string MaintSummary_ItemName {
            get {
                return ResourceManager.GetString("MaintSummary_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s type..
        /// </summary>
        public static string MaintSummary_ItemType {
            get {
                return ResourceManager.GetString("MaintSummary_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;]&apos;s [&apos;Location&apos;]..
        /// </summary>
        public static string MaintSummary_Location {
            get {
                return ResourceManager.GetString("MaintSummary_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;]&apos;s [&apos;MasterCategory&apos;].
        /// </summary>
        public static string MaintSummary_MasterCategory {
            get {
                return ResourceManager.GetString("MaintSummary_MasterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&apos;Item&apos;]&apos;s Org. Unit..
        /// </summary>
        public static string MaintSummary_OrgUnit {
            get {
                return ResourceManager.GetString("MaintSummary_OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service order type (fixed/flow).
        /// </summary>
        public static string MaintSummary_PlanTypeCategory {
            get {
                return ResourceManager.GetString("MaintSummary_PlanTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual plan of the repair order or had done service order..
        /// </summary>
        public static string MaintSummary_ViewCategory {
            get {
                return ResourceManager.GetString("MaintSummary_ViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search summary for specified year..
        /// </summary>
        public static string MaintSummary_Year {
            get {
                return ResourceManager.GetString("MaintSummary_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection function switch will affect this switch, if the inspection function is turned off, this switch will automatically set to close..
        /// </summary>
        public static string MasterOrderSwitchDescription {
            get {
                return ResourceManager.GetString("MasterOrderSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to approve the order.
        /// </summary>
        public static string OrderPage_ApproveBy {
            get {
                return ResourceManager.GetString("OrderPage_ApproveBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the approve order result.
        /// </summary>
        public static string OrderPage_ApproveResult {
            get {
                return ResourceManager.GetString("OrderPage_ApproveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recode the approve order remark.
        /// </summary>
        public static string OrderPage_ApproveResultRemark {
            get {
                return ResourceManager.GetString("OrderPage_ApproveResultRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to cal the order.
        /// </summary>
        public static string OrderPage_CalBy {
            get {
                return ResourceManager.GetString("OrderPage_CalBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the completion date for actually calibration.
        /// </summary>
        public static string OrderPage_CalCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_CalCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order&apos;s estimate service date.
        /// </summary>
        public static string OrderPage_CalEstimateServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_CalEstimateServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order&apos;s estimate service duration.
        /// </summary>
        public static string OrderPage_CalEstimateServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_CalEstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recode the cal order remark.
        /// </summary>
        public static string OrderPage_CalRemarkTitle {
            get {
                return ResourceManager.GetString("OrderPage_CalRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the cal order result.
        /// </summary>
        public static string OrderPage_CalResult {
            get {
                return ResourceManager.GetString("OrderPage_CalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the actual duration for cal order.
        /// </summary>
        public static string OrderPage_CalServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_CalServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reason to cancel the order.
        /// </summary>
        public static string OrderPage_CancelReason {
            get {
                return ResourceManager.GetString("OrderPage_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to check the order.
        /// </summary>
        public static string OrderPage_CheckBy {
            get {
                return ResourceManager.GetString("OrderPage_CheckBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to check in the order.
        /// </summary>
        public static string OrderPage_CheckInBy {
            get {
                return ResourceManager.GetString("OrderPage_CheckInBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In Date.
        /// </summary>
        public static string OrderPage_CheckInDate {
            get {
                return ResourceManager.GetString("OrderPage_CheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the check order result.
        /// </summary>
        public static string OrderPage_CheckResult {
            get {
                return ResourceManager.GetString("OrderPage_CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recode the check order remark.
        /// </summary>
        public static string OrderPage_CheckResultRemark {
            get {
                return ResourceManager.GetString("OrderPage_CheckResultRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a order&apos;s control.
        /// </summary>
        public static string OrderPage_Control {
            get {
                return ResourceManager.GetString("OrderPage_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a date to extend the order.
        /// </summary>
        public static string OrderPage_ExtendServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_ExtendServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Party.
        /// </summary>
        public static string OrderPage_ExternalParty {
            get {
                return ResourceManager.GetString("OrderPage_ExternalParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string OrderPage_FollowUp {
            get {
                return ResourceManager.GetString("OrderPage_FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up Date.
        /// </summary>
        public static string OrderPage_FollowUpDate {
            get {
                return ResourceManager.GetString("OrderPage_FollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to inspection the order.
        /// </summary>
        public static string OrderPage_InspectionBy {
            get {
                return ResourceManager.GetString("OrderPage_InspectionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is Internal or External.
        /// </summary>
        public static string OrderPage_InternalExternal {
            get {
                return ResourceManager.GetString("OrderPage_InternalExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is priority.
        /// </summary>
        public static string OrderPage_IsPriority {
            get {
                return ResourceManager.GetString("OrderPage_IsPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the completion date for maint(repair) order.
        /// </summary>
        public static string OrderPage_MaintCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order&apos;s estimate service date.
        /// </summary>
        public static string OrderPage_MaintEstimateServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintEstimateServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order&apos;s estimate service duration.
        /// </summary>
        public static string OrderPage_MaintEstimateServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_MaintEstimateServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maint order&apos;s follow up date.
        /// </summary>
        public static string OrderPage_MaintFollowUpDate {
            get {
                return ResourceManager.GetString("OrderPage_MaintFollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recode the maint order remark.
        /// </summary>
        public static string OrderPage_MaintRemarkTitle {
            get {
                return ResourceManager.GetString("OrderPage_MaintRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the maint order result.
        /// </summary>
        public static string OrderPage_MaintResultTitle {
            get {
                return ResourceManager.GetString("OrderPage_MaintResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the duration for maint(repair) order.
        /// </summary>
        public static string OrderPage_MaintServiceDuration {
            get {
                return ResourceManager.GetString("OrderPage_MaintServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to measure the order.
        /// </summary>
        public static string OrderPage_MeasureBy {
            get {
                return ResourceManager.GetString("OrderPage_MeasureBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input next cal date.
        /// </summary>
        public static string OrderPage_NextCalDate {
            get {
                return ResourceManager.GetString("OrderPage_NextCalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recode the order remark.
        /// </summary>
        public static string OrderPage_Remark {
            get {
                return ResourceManager.GetString("OrderPage_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user to review the order.
        /// </summary>
        public static string OrderPage_ReviewBy {
            get {
                return ResourceManager.GetString("OrderPage_ReviewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the review order result.
        /// </summary>
        public static string OrderPage_ReviewResult {
            get {
                return ResourceManager.GetString("OrderPage_ReviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the standard deviation for order.
        /// </summary>
        public static string OrderPage_StandardDeviation {
            get {
                return ResourceManager.GetString("OrderPage_StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the completion date for task order.
        /// </summary>
        public static string OrderPage_TaskCompletionServiceDate {
            get {
                return ResourceManager.GetString("OrderPage_TaskCompletionServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the TI&apos;s word content.
        /// </summary>
        public static string OrderPage_WordContent {
            get {
                return ResourceManager.GetString("OrderPage_WordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgUnit&apos;s Name.
        /// </summary>
        public static string OrgUnit_Name {
            get {
                return ResourceManager.GetString("OrgUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new [&apos;Item&apos;], you can select an &quot;[&apos;Item&apos;] Template&quot; for editing.  Alternatively, you can select &quot;Empty Template&quot; to start from scratch..
        /// </summary>
        public static string Page_Templation {
            get {
                return ResourceManager.GetString("Page_Templation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a password containing letters.
        /// </summary>
        public static string PasswordPolicy_ContainLetter {
            get {
                return ResourceManager.GetString("PasswordPolicy_ContainLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a password containing number.
        /// </summary>
        public static string PasswordPolicy_ContainNumber {
            get {
                return ResourceManager.GetString("PasswordPolicy_ContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum password length.
        /// </summary>
        public static string PasswordPolicy_MaxLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum letter times.
        /// </summary>
        public static string PasswordPolicy_MinEnLetterLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MinEnLetterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum password length.
        /// </summary>
        public static string PasswordPolicy_MinLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a password containing special char.
        /// </summary>
        public static string PasswordPolicy_NeedSpecialChar {
            get {
                return ResourceManager.GetString("PasswordPolicy_NeedSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a password containing space.
        /// </summary>
        public static string PasswordPolicy_NoBlankSpace {
            get {
                return ResourceManager.GetString("PasswordPolicy_NoBlankSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Repeat Interval frequency.
        /// </summary>
        public static string PasswordPolicy_UnlikePrePwdCount {
            get {
                return ResourceManager.GetString("PasswordPolicy_UnlikePrePwdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnaround Time Analysis Service month.
        /// </summary>
        public static string Report_TurnaroundTimeAnalysis_ServiceMonth {
            get {
                return ResourceManager.GetString("Report_TurnaroundTimeAnalysis_ServiceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Formating.
        /// </summary>
        public static string Report_Type {
            get {
                return ResourceManager.GetString("Report_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve {0} order while order is complete..
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationApproval {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this calibration order&apos;s work memebers and managent memebers..
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationAssign {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in {0} order..
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationCheckIn {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend(Delayed) {0} order..
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationExtend {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review {0} order while order is in approval..
        /// </summary>
        public static string ServiceOrderActionDetail_CalibrationReview {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CalibrationReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign memebers for this {0} order..
        /// </summary>
        public static string ServiceOrderActionDetail_CommonAssign {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this {0} order..
        /// </summary>
        public static string ServiceOrderActionDetail_CommonCancel {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in {0} order while order is complete..
        /// </summary>
        public static string ServiceOrderActionDetail_CommonCheckIn {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute {0} work for {0} order..
        /// </summary>
        public static string ServiceOrderActionDetail_CommonExecute {
            get {
                return ResourceManager.GetString("ServiceOrderActionDetail_CommonExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string SystemCheck_Body {
            get {
                return ResourceManager.GetString("SystemCheck_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string SystemCheck_Receiver {
            get {
                return ResourceManager.GetString("SystemCheck_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SystemCheck_Subject {
            get {
                return ResourceManager.GetString("SystemCheck_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Item.
        /// </summary>
        public static string TaskPage_ManagementItem {
            get {
                return ResourceManager.GetString("TaskPage_ManagementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Notify.
        /// </summary>
        public static string TaskPage_NeedNotify {
            get {
                return ResourceManager.GetString("TaskPage_NeedNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TaskPage_Project {
            get {
                return ResourceManager.GetString("TaskPage_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Level.
        /// </summary>
        public static string TaskPage_RiskLevel {
            get {
                return ResourceManager.GetString("TaskPage_RiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection function switch will affect this switch, if the inspection function is turned off, this switch will automatically set to close..
        /// </summary>
        public static string TaskSwitchDescription {
            get {
                return ResourceManager.GetString("TaskSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template&apos;s Management Item.
        /// </summary>
        public static string TaskTypePage_ManagementItem {
            get {
                return ResourceManager.GetString("TaskTypePage_ManagementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template&apos;s Project.
        /// </summary>
        public static string TaskTypePage_Project {
            get {
                return ResourceManager.GetString("TaskTypePage_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template&apos;s Remark.
        /// </summary>
        public static string TaskTypePage_Remark {
            get {
                return ResourceManager.GetString("TaskTypePage_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template&apos;s Name, must be unique.
        /// </summary>
        public static string TaskTypePage_TaskTypeName {
            get {
                return ResourceManager.GetString("TaskTypePage_TaskTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template&apos;s Risk Level.
        /// </summary>
        public static string TaskTypePage_TaskTypeRiskLevel {
            get {
                return ResourceManager.GetString("TaskTypePage_TaskTypeRiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team&apos;s Description.
        /// </summary>
        public static string Team_Description {
            get {
                return ResourceManager.GetString("Team_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team&apos;s Name.
        /// </summary>
        public static string Team_Name {
            get {
                return ResourceManager.GetString("Team_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team&apos;s Type.
        /// </summary>
        public static string Team_TeamType {
            get {
                return ResourceManager.GetString("Team_TeamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team&apos;s Users.
        /// </summary>
        public static string Team_User {
            get {
                return ResourceManager.GetString("Team_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Company.If user doesn&apos;t only have Sysadmin Administrator Role, Company is require..
        /// </summary>
        public static string User_Company {
            get {
                return ResourceManager.GetString("User_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Full Name.
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users access the default language.
        /// </summary>
        public static string User_Language {
            get {
                return ResourceManager.GetString("User_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Logon Name.
        /// </summary>
        public static string User_LogonName {
            get {
                return ResourceManager.GetString("User_LogonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Roles.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Title.
        /// </summary>
        public static string UserPage_Title_Colon {
            get {
                return ResourceManager.GetString("UserPage_Title_Colon", resourceCulture);
            }
        }
    }
}
